# .github/workflows/publish.yml
# https://dart.dev/tools/pub/automated-publishing
name: Publish to pub.dev

on:
  push:
    tags:
       - v*
    branches:
       - main


jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Install dependencies
        run: dart analyze
      - name: Install dependencies
        run: dart test
      - name: Publish
        run: dart pub publish --force
